name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        env:
          # The username of the actions runner that postgres defaults to
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      env:
        NODE_ENV: test
      with:
        node-version: 12.x
    - name: Cache node_modules
      id: cache-primes
      uses: actions/cache@v1
      with:
        path: ./node_modules
        key: ${{ runner.os }}-${{hashFiles('**/package-lock.json')}}-node_modules
    - name: NPM Install
      env:
        NODE_ENV: test
      run: npm install --no-audit
    - name: DB Setup
      env:
        NODE_ENV: test
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: |
        ./node_modules/.bin/sequelize db:create --env test
        ./node_modules/.bin/sequelize db:migrate --env test
    - name: Run tests
      env:
        NODE_ENV: test
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: npm test
